updated deploy to ec2 job on ci-cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -81,10 +81,11 @@ jobs:
   deploy:
     name: Deploying on EC2 via SSH
     if: ${{ github.event_name == 'push' }}
-    needs: [build-test]
+    needs: [ build-test ]
     runs-on: ubuntu-latest
+
     steps:
-      - name: Deploying Application on EC2
+      - name: Deploy Application on EC2
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SSH_EC2_IP }}
@@ -92,5 +93,10 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           passphrase: ${{ secrets.SSH_PASSPHRASE }}
           script: |
-            cd ~/.scripts
-            ./docker-ec2-deply.sh
+            mkdir -p ~/.scripts
+            if [ ! -f ~/.scripts/docker-ec2-deploy.sh ]; then
+              echo "Error: docker-ec2-deploy.sh not found!"
+              exit 1
+            fi
+            chmod +x ~/.scripts/docker-ec2-deploy.sh
+            ./docker-ec2-deploy.sh
